# Generated by Django 5.0.3 on 2024-04-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_student_teacher_student_teachers_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='quantity',
        ),
    ]
