# Generated by Django 5.0.3 on 2024-04-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_enrollment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
