# Generated by Django 5.0.3 on 2024-04-09 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_rename_teacher_student_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='school.student'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='teachers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='school.teacher'),
        ),
    ]
