# Generated by Django 5.0.3 on 2024-04-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_enrollment_students_alter_enrollment_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(related_name='students', through='school.Enrollment', to='school.teacher'),
        ),
    ]
