# Generated by Django 5.0.3 on 2024-04-11 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_alter_enrollment_id_alter_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.student'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='teachers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='school.teacher'),
        ),
    ]
