# Generated by Django 5.0.3 on 2024-04-11 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_alter_enrollment_students_alter_enrollment_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teachers',
        ),
    ]
