# Generated by Django 4.2.7 on 2024-01-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Альтер.название модели'),
        ),
    ]
